### ISSUE TITLE
updateIMU problem with parameters in AQUA

### ISSUE THREAD

**Issue by JessicaBertolasi** [Mayitzin/ahrs#85]
Hi, I'm trying to calculate quaternions with AQUA filter - using only acc and gyro.
I actually implemented this
```
for index in range(len(timestamp)):
    q[index] = AQUA.estimate(AQUA, accelerometer[index])
    q1[index] = AQUA.updateIMU(AQUA, q[index], gyroscope[index], accelerometer[index])
```
  where timestamp define the legth of the document where to get the datas.

It return me an error on q1
```
Traceback (most recent call last):
  File "quaternion.py", line 60, in <module>
    q1[index] = AQUA.updateIMU(AQUA, q[index], gyroscope[index], accelerometer[index])
  File "/home/jessicab/.local/lib/python3.8/site-packages/ahrs/filters/aqua.py", line 941, in updateIMU
    qDot = 0.5*self.Omega(gyr) @ q                      # Quaternion derivative (eq. 39)
TypeError: Omega() missing 1 required positional argument: 'x'
```
how can I fix it? I still tried to edit `qDot = 0.5*self.Omega(gyr) @ q`  in `qDot = 0.5*self.Omega(AQUA,gyr) @ q ` directly from source library but after that it returns me an error on the successive line `qInt = q + qDot*self.Dt` that says that `AttributeError: type object 'AQUA' has no attribute 'Dt'`

how can I fix it and find quaternions? thank you so much!

**Comment by Mayitzin** [comment]
Hi,

I see you are using the methods of the class directly as functions.

In this case you have to first construct the class `AQUA`, which will automatically define its attributes, like the time step Dt. Then, you can use the methods as you intend:

You also have to compute the first out of your loop, otherwise, it will keep estimating it at every iteration.

```python
import numpy as np      # To create an array you can iterate over
import ahrs
aqua = ahrs.AQUA()                      # Create an AQUA object (automatically defines Dt as part of it)
num_samples = len(timestamp)            # Number of total samples to use (based on your timestamp array)
q = np.zeros((num_samples, 4))          # Initialize an array to save your quaternions into.
q[0] = aqua.estimate(accelerometer[0])  # Estimate first quaternion using Accelerometer only
for index in range(1, num_samples+1):
    aqua.Dt = timestamp[index] - timestamp[index-1]  # Re-define the time step Dt
    q[index] = aqua.updateIMU(q[index-1], gyroscope[index], accelerometer[index])
```

That's it. With this, you re-define the time step (difference between current and previous time stamp) at every iteration, and use this to compute the current orientation, until you reach the end of the recording.

Make sure there are the same number of time stamps, acceleration measurements, and gyroscope measurements. And give the angular velocity (gyroscopes) as rad/s.

Mario.
